### ISSUE TITLE
Icon in map is not positioned correctly

### ISSUE THREAD

**Issue by jaortiz117** [UPRM-Moonbuggy-Telemetry/BuggyTelemetryWebApp#13]
This is because the parent element has no available top object. Maybe it is due to bootstrap or something style related

**Comment by UPRMMoonBuggy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix GPS location bug #13](https://trello.com/c/4hSTe7jE/33-fix-gps-location-bug-13)

**Comment by jaortiz117** [comment]
This is to be fixed in #53
